workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store # or 'development' for testing
        bundle_identifier: com.example.musiClone # Replace with your Bundle ID
      vars:
        APP_STORE_APPLE_ID: "+919560875024" # From App Store Connect
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build IPA
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - sdevider@gmail.com # Replace with your email
        notify:
          success: true
          failure: true
      app_store_connect: # Optional, for TestFlight
        auth: integration